language: cpp
os:
  - osx
  - linux
sudo: required
dist: trusty
compiler:
  - gcc
addons:
  apt:
    packages:
      - g++-4.8
      - gcc-4.8
      - libegl1-mesa-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxrender-dev
      - libxtst-dev
before_script:
  - ./travis/setup.sh
script:
  - ./travis/build.sh
