language: cpp
os:
  # - osx
  - linux
env:
  - BUILD_TARGET=device
  # - BUILD_TARGET=host
sudo: required
dist: trusty
compiler:
  - gcc
addons:
  apt:
    packages:
      - g++-4.8
      - gcc-4.8
      - libegl1-mesa-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxrender-dev
      - libxtst-dev
      # Needed for Android builds:
      - ant
      - gcc-multilib
      - lib32stdc++6
      - lib32z1
      - libncurses5:i386
      - libstdc++6:i386
      - openjdk-7-jdk
      - openjdk-7-jre
      - zlib1g:i386
before_script:
  - ./travis/setup.sh
script:
  - ./travis/build.sh
